//! Generates i18n_catalog.rs embedding all .mo translation files so the
//! binary is self-contained (no libintl needed, Windows-friendly).

use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=../mcomix/messages");
    let messages = Path::new("../mcomix/messages");
    let mut langs: Vec<String> = Vec::new();
    if let Ok(rd) = fs::read_dir(messages) {
        for e in rd.flatten() {
            if e.path().is_dir() {
                let mo = e.path().join("LC_MESSAGES").join("mcomix.mo");
                if mo.is_file() {
                    if let Some(name) = e.file_name().to_str() {
                        langs.push(name.to_string());
                    }
                }
            }
        }
    }
    langs.sort();

    let mut out = String::from("// @generated by build.rs — do not edit.\n");
    out.push_str("pub const CATALOG: &[(&str, &[u8])] = &[\n");
    for lang in &langs {
        let abs = messages
            .canonicalize()
            .unwrap_or_else(|_| messages.to_path_buf())
            .join(lang)
            .join("LC_MESSAGES")
            .join("mcomix.mo");
        let abs = abs.to_string_lossy().replace('\\', "/");
        out.push_str(&format!(
            "    (\"{lang}\", include_bytes!(\"{abs}\")),\n"
        ));
    }
    out.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("i18n_catalog.rs"), out).expect("write catalog");
}
